# -*- coding: utf-8 -*-
"""Exercise 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vlG8QFiRr0F816z03a8s-BU1XJEvFQpA

#Exercise 1

Goal: Build, train, and verify an SVR pipeline on Position_Salaries.csv

##Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""##Importing the dataset"""

dataset = pd.read_csv('Position_Salaries.csv')

print(dataset)

dataset.head()

"""##Creating the matrix of features"""

X = dataset.iloc[:, 1:-1].values

print(X)

X.shape

"""##Creating the dependent variable vector"""

y = dataset.iloc[:, -1].values

print(y)

y.shape

"""##Transforming the dependent variable vector into a 2D array"""

y = y.reshape(-1, 1)

print(y)

y.shape

"""##Feature Scaling"""

from sklearn.preprocessing import StandardScaler

"""###Feature scaling on matrix of features"""

sc_X = StandardScaler()
X_scaled = sc_X.fit_transform(X)

print(X_scaled)

"""###Feature scaling on dependent variable vector"""

sc_y = StandardScaler()
y_scaled = sc_y.fit_transform(y)

print(y_scaled)

"""##Building the model"""

from sklearn.svm import SVR
regressor = SVR(kernel='rbf')

"""##Training the model"""

regressor.fit(X_scaled, y_scaled)

"""##Making a single prediction"""

pred_scaled = regressor.predict(sc_X.transform([[6.5]]))
pred = sc_y.inverse_transform(pred_scaled.reshape(-1, 1))

print(pred)

"""##Visualizing the results"""

plt.scatter(X, y, color='red')
plt.plot(X, sc_y.inverse_transform(regressor.predict(X_scaled).reshape(-1, 1)), color='blue')
plt.title('Position Levels vs Salaries')
plt.xlabel('Position Levels')
plt.ylabel('Salaries')
plt.show()