# -*- coding: utf-8 -*-
"""Exercise 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1npOuw6fK0Cx1-LxMdIkf4ygLMZaK8exX

#Exercise: Polynomial Regression for Product Sales Prediction

Goal: Build a complete polynomial regression model to predict product sales based on advertising budget, transforming linear features into polynomial features and visualizing the curved relationship

##Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""##Importing the dataset"""

dataset = pd.read_csv('advertising_sales_dataset.csv')

print(dataset)

"""##Creating the matrix of features"""

X = dataset.iloc[:, :-1].values

print(X)

"""##Creating the dependent variable vector"""

y = dataset.iloc[:, -1].values

print(y)

"""##Creating a new matrix of features"""

from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree=3)
X_poly = poly_reg.fit_transform(X)

print(X_poly)

"""##Building the model"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

"""##Training the model"""

regressor.fit(X_poly, y)

"""##Visualizing the results"""

plt.scatter(X, y, color='red')
plt.plot(X, regressor.predict(X_poly), color='blue')
plt.title('Advertising Budgets vs Sales (degree=3)')
plt.xlabel('Advertising Budgets')
plt.ylabel('Sales')
plt.show()

"""##Making a single prediction"""

#Make a prediction for a new advertising budget value of 75 thousand
print(regressor.predict(poly_reg.transform([[75]])))