# -*- coding: utf-8 -*-
"""Simple Linear Regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pLvGcNJWSBkVSM98Khs7aUAMKawSdlJa

#Simple Linear Regression

##Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""##Import the dataset"""

dataset = pd.read_csv('Salary_Data.csv')

print(dataset)

"""##Creating the matrix of features"""

X = dataset.iloc[:, :-1].values

print(X)

"""##Creating the dependent variable vector"""

y = dataset.iloc[:, -1].values

print(y)

"""##Splitting the dataset into training set and test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(X_train)

print(X_test)

print(y_train)

print(y_test)

"""##Building the model"""

from sklearn.linear_model import LinearRegression
slr = LinearRegression()

"""##Training the model"""

slr.fit(X_train, y_train)

"""##Predicting the test set results"""

y_pred = slr.predict(X_test)

print(y_pred)

"""##Visualizing the training set results"""

plt.scatter(X_train, y_train, color='red')
plt.plot(X_train, slr.predict(X_train), color='blue')
plt.title('Years of Experience vs Salary (Training Set)')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()

"""##Visualizing the test set results"""

plt.scatter(X_test, y_test, color='red')
plt.plot(X_test, y_pred, color='blue')
plt.title('Years of Experience vs Salary (Test Set)')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()

"""##Making a single prediction"""

#Predicting the salary of an employee with 12 years of experience
print(slr.predict([[12]]))

"""##Calculating the values of the coefficients

###Calculating b<sub>0</sub> (y-intercept)
"""

print(slr.intercept_)

"""###Calculating b<sub>1</sub> (slope coefficient)"""

print(slr.coef_)