# -*- coding: utf-8 -*-
"""Random Forest Regressor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dBKgRqnSDNrxZ3GMf51xBORZfcVwyLRQ

#Random Forest Regression

##Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""##Importing the dataset"""

dataset = pd.read_csv('Position_Salaries.csv')

print(dataset)

"""##Creating the matrix of features"""

X = dataset.iloc[:, 1:-1].values

print(X)

"""##Creating the dependent variable vector"""

y = dataset.iloc[:, -1].values

print(y)

"""##Building the model"""

from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=10, random_state=0)

"""##Training the model"""

regressor.fit(X, y)

"""##Making a prediction"""

print(regressor.predict([[6.5]]))

"""##Visualizing the results in higher resolution"""

X_grid = np.arange(min(X), max(X), 0.01)
X_grid = X_grid.reshape(len(X_grid), 1)
plt.scatter(X, y, color='red')
plt.plot(X_grid, regressor.predict(X_grid), color='blue')
plt.title('Position Levels vs Salaries')
plt.xlabel('Position Levels')
plt.ylabel('Salaries')
plt.show()