# -*- coding: utf-8 -*-
"""Exercise 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P1WL3mxZy_T5mstqiIhAZePjCPPxQEDw

#Exercise: House Price Prediction

Goal: Build a multiple linear regression model to predict house prices using multiple features including categorical data.

##Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""##Importing the dataset"""

dataset = pd.read_csv('houses_dataset.csv')

print(dataset)

"""##Creating the matrix of features"""

X = dataset.iloc[:, 1:-1].values

print(X)

"""##Creating the dependent variable vector"""

y = dataset.iloc[:, -1].values

print(y)

"""##Encoding categorical data

###Encoding the independent variable
"""

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

print(X)

"""##Splitting the dataset into training set and test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

print(X_train)

print(X_test)

print(y_train)

print(y_test)

"""##Building the model"""

from sklearn.linear_model import LinearRegression
mlr = LinearRegression()

"""##Training the model"""

mlr.fit(X_train, y_train)

"""##Predicting the test set results"""

y_pred = mlr.predict(X_test)

print(y_pred)

"""##Display the predicted and actual test set results"""

np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), axis=1))

"""##Making a single prediction"""

#Make a single prediction for a house with Size: 2000 sqft, Bedrooms: 3, Age: 8 years, Neighborhood: 'B'
print(mlr.predict([[0, 1, 0, 2000, 3, 8]]))

"""##Calculating the values of the coefficients

###Calculating b<sub>0</sub> (y-intercept)
"""

print(mlr.intercept_)

"""###Calculating b<sub>i</sub> (slope coefficients)"""

print(mlr.coef_)

"""###Calculate the prediction manually using the formula: y = b<sub>0</sub> + b<sub>1</sub>*x<sub>1</sub> + b<sub>2</sub>*x<sub>2</sub> + ... and verify it matches your model's prediction."""

print(mlr.intercept_ + 0*mlr.coef_[0] + 1*mlr.coef_[1] + 0*mlr.coef_[2] + 2000*mlr.coef_[3] + 3*mlr.coef_[4] + 8*mlr.coef_[5])