# -*- coding: utf-8 -*-
"""Exercise 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wopM15xK9pLr0B1GbZ61zTzkMqa5tuar

#Exercise 1

Goal: Train an Decision Tree regression model on Position_Salaries.csv, make the single prediction for level 6.5, and produce the higher-resolution plot

##Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""##Importing the dataset"""

dataset = pd.read_csv('Position_Salaries.csv')

print(dataset)

dataset.head()

"""##Creating the matrix of features"""

X = dataset.iloc[:, 1:-1].values

print(X)

X.shape

"""##Creating the dependent variable vector"""

y = dataset.iloc[:, -1].values

print(y)

y.shape

"""##Building the model"""

from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state=0)

"""##Training the model"""

regressor.fit(X, y)

"""##Making a prediction"""

pred_6_5 = regressor.predict([[6.5]])

print(pred_6_5)

"""##Visualizing the results in higher resolution"""

X_grid = np.arange(min(X), max(X), 0.1)
X_grid = X_grid.reshape(len(X_grid), 1)
plt.scatter(X, y, color='red')
plt.plot(X_grid, regressor.predict(X_grid), color='blue')
plt.title('Position Levels vs Salaries')
plt.xlabel('Position Levels')
plt.ylabel('Salaries')
plt.show()