# -*- coding: utf-8 -*-
"""Exercise 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18YuMPcofA-szqx664hRAfroTB8-cujez

#Exercise: Support Vector Regression for Equipment Price Prediction

Goal: Build a complete SVR model to predict industrial equipment prices based on usage hours, with proper feature scaling for both features and target, followed by inverse transformation for predictions

##Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""##Importing the dataset"""

dataset = pd.read_csv('equipment_usage_price.csv')

print(dataset)

"""##Creating the matrix of features"""

X = dataset.iloc[:, :-1].values

print(X)

"""##Creating the dependent variable vector"""

y = dataset.iloc[:, -1].values

print(y)

"""##Transforming the dependent variable vector into a 2D array"""

y = y.reshape(-1, 1)

print(y)

"""##Feature Scaling"""

from sklearn.preprocessing import StandardScaler

"""###Feature scaling on matrix of features"""

sc_X = StandardScaler()
X_scaled = sc_X.fit_transform(X)

print(X_scaled)

"""###Feature scaling on dependent variable vector"""

sc_y = StandardScaler()
y_scaled = sc_y.fit_transform(y)

print(y_scaled)

"""##Building the model"""

from sklearn.svm import SVR
regressor = SVR(kernel='rbf')

"""##Training the model"""

regressor.fit(X_scaled, y_scaled)

"""##Making a single prediction"""

print(sc_y.inverse_transform(regressor.predict(sc_X.transform([[2500]])).reshape(-1, 1)))

"""##Visualizing the results"""

plt.scatter(X, y, color='red')
plt.plot(X, sc_y.inverse_transform(regressor.predict(X_scaled).reshape(-1, 1)), color='blue')
plt.title('Equipment Usage Hours vs Equipment Price')
plt.xlabel('Equipment Usage Hours')
plt.ylabel('Equipment Price')
plt.show()