# -*- coding: utf-8 -*-
"""Exercise 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fmuz_ri-hsQuh5Kokjhzclvv8F2K2x60

#Exercise: Decision Tree Regression for Customer Spending Prediction

Goal: Build a complete decision tree regression model to predict customer spending based on loyalty points, with high-resolution visualization showing the step-like decision boundaries

##Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""##Importing the dataset"""

dataset = pd.read_csv('loyalty_spending_dataset.csv')

print(dataset)

"""##Creating the matrix of features"""

X = dataset.iloc[:, :-1].values

print(X)

"""##Creating the dependent variable vector"""

y = dataset.iloc[:, -1].values

print(y)

"""##Building the model"""

from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state=0)

"""##Training the model"""

regressor.fit(X, y)

"""##Making a prediction"""

#Make a single prediction for a customer with 650 loyalty points
print(regressor.predict([[650]]))

"""##Visualizing the results in higher resolution"""

X_grid = np.arange(min(X), max(X), 0.01)
X_grid = X_grid.reshape(len(X_grid), 1)
plt.scatter(X, y, color='red')
plt.plot(X_grid, regressor.predict(X_grid), color='blue')
plt.title('Loyalty Points vs Monthly Spending')
plt.xlabel('Loyalty Points')
plt.ylabel('Monthly Spending')
plt.show()