# -*- coding: utf-8 -*-
"""Exercise 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18yTx3krHmghv2oEMbwAdiHzIN12bS1VC

#Exercise: Random Forest Regression for Property Value Prediction

Goal: Build a complete random forest regression model to predict property values based on property age, with high-resolution visualization showing the ensemble's averaged predictions

##Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""##Importing the dataset"""

dataset = pd.read_csv('property_dataset.csv')

print(dataset)

"""##Creating the matrix of features"""

X = dataset.iloc[:, :-1].values

print(X)

"""##Creating the dependent variable vector"""

y = dataset.iloc[:, -1].values

print(y)

"""##Building the model"""

from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=10, random_state=0)

"""##Training the model"""

regressor.fit(X, y)

"""##Making a prediction"""

#Make a single prediction for a property that is 7.5 years old
print(regressor.predict([[7.5]]))

"""##Visualizing the results in higher resolution"""

X_grid = np.arange(min(X), max(X), 0.01)
X_grid = X_grid.reshape(len(X_grid), 1)
plt.scatter(X, y, color='red')
plt.plot(X_grid, regressor.predict(X_grid), color='blue')
plt.title('Property Age vs Property Value')
plt.xlabel('Property Age')
plt.ylabel('Property Value')
plt.show()