# -*- coding: utf-8 -*-
"""Exercise 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NcYjjjC-1zNsyAV9mOsKdUC-qMcsqB1m

#Exercise: Simple Linear Regression Implementation

Goal: Build a complete simple linear regression model from scratch to predict house prices based on area, including visualization and coefficient analysis

##Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""##Importing the dataset"""

dataset = pd.read_csv('house_dataset.csv')

print(dataset)

"""##Creating the matrix of features"""

X = dataset.iloc[:, :-1].values

print(X)

"""##Creating the dependent variable vector"""

y = dataset.iloc[:, -1].values

print(y)

"""##Splitting the dataset into training set and test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(X_train)

print(X_test)

print(y_train)

print(y_test)

"""##Building the model"""

from sklearn.linear_model import LinearRegression
slr = LinearRegression()

"""##Training the model"""

slr.fit(X_train, y_train)

"""##Predicting the test set results"""

y_pred = slr.predict(X_test)

print(y_pred)

"""##Visualizing the training set results"""

plt.scatter(X_train, y_train, color='red')
plt.plot(X_train, slr.predict(X_train), color='blue')
plt.title('Area vs House Price (Training set)')
plt.xlabel('Area (sqft)')
plt.ylabel('House Price')
plt.show()

"""##Visualizing the test set results"""

plt.scatter(X_test, y_test, color='red')
plt.plot(X_test, y_pred, color='blue')
plt.title('Area vs House Price (Test set)')
plt.xlabel('Area (sqft)')
plt.ylabel('House Price')
plt.show()

"""##Making a single prediction"""

#Make a single prediction for a house with 1800 sq ft area
print(slr.predict([[1800]]))

"""##Calculating the values of the coefficients

###Calculating b<sub>0</sub> (y-intercept)
"""

print(slr.intercept_)

"""###Calculating b<sub>1</sub> (slope coefficient)"""

print(slr.coef_)