# -*- coding: utf-8 -*-
"""Support Vector Regression (SVR)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dkv6aYzOHSPIPj6aQcNBoZRpVTq1JPZj

#Supoort Vector Regression (SVR)

##Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""##Importing the dataset"""

dataset = pd.read_csv('Position_Salaries.csv')

print(dataset)

"""##Creating the matrix of features"""

X = dataset.iloc[:, 1:-1].values

print(X)

"""##Creating the dependent variable vector"""

y = dataset.iloc[:, -1].values

print(y)

"""##Transforming the dependent variable vector into a 2D array"""

y = y.reshape(len(y), 1)

print(y)

"""##Feature Scaling"""

from sklearn.preprocessing import StandardScaler

"""###Feature scaling on matrix of features"""

sc_X = StandardScaler()
X = sc_X.fit_transform(X)

print(X)

"""###Feature scaling on dependent variable vector"""

sc_y = StandardScaler()
y = sc_y.fit_transform(y)

print(y)

"""##Building the SVR model"""

from sklearn.svm import SVR
regressor = SVR(kernel='rbf')

"""##Training the SVR model"""

regressor.fit(X, y)

"""##Making a single prediction"""

print(sc_y.inverse_transform(regressor.predict(sc_X.transform([[6.5]])).reshape(-1, 1)))

"""##Visualizing the results"""

plt.scatter(sc_X.inverse_transform(X), sc_y.inverse_transform(y), color='red')
plt.plot(sc_X.inverse_transform(X), sc_y.inverse_transform(regressor.predict(X).reshape(-1, 1)), color='blue')
plt.title('Position Levels vs Salaries')
plt.xlabel('Position Levels')
plt.ylabel('Salaries')
plt.show()