# -*- coding: utf-8 -*-
"""Exercise 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1izV971F3QxLGJz1wZBszgy5GUTDUNdvL

#Exercise: Restaurant Location vs Daily Revenue

Goal: Build a random forest regression model to predict daily restaurant revenue based on location characteristics, using the ensemble power of multiple decision trees.

##Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""##Importing the dataset"""

dataset = pd.read_csv('restaurant_locations_dataset.csv')

print(dataset)

"""##Creating the matrix of features"""

X = dataset.iloc[:, 1:-1].values

print(X)

"""##Creating the dependent variable vector"""

y = dataset.iloc[:, -1].values

print(y)

"""##Building the model

###Building the model with 10 estimators
"""

from sklearn.ensemble import RandomForestRegressor
regressor_10 = RandomForestRegressor(n_estimators=10, random_state=0)

"""###Building the model with 50 estimators"""

from sklearn.ensemble import RandomForestRegressor
regressor_50 = RandomForestRegressor(n_estimators=50, random_state=0)

"""###Building the model with 100 estimators"""

from sklearn.ensemble import RandomForestRegressor
regressor_100 = RandomForestRegressor(n_estimators=100, random_state=0)

"""##Training the model

###Training the model with 10 estimators
"""

regressor_10.fit(X, y)

"""###Training the model with 50 estimators"""

regressor_50.fit(X, y)

"""###Training the model with 100 estimators"""

regressor_100.fit(X, y)

"""##Making a prediction

###Making a prediction for model with 10 estimators
"""

#Predict revenue for location scores 30, 70, and 90
print(regressor_10.predict([[30]]))
print(regressor_10.predict([[70]]))
print(regressor_10.predict([[90]]))

"""###Making a prediction for model with 50 estimators"""

#Predict revenue for location scores 30, 70, and 90
print(regressor_50.predict([[30]]))
print(regressor_50.predict([[70]]))
print(regressor_50.predict([[90]]))

"""###Making a prediction for model with 100 estimators"""

#Predict revenue for location scores 30, 70, and 90
print(regressor_100.predict([[30]]))
print(regressor_100.predict([[70]]))
print(regressor_100.predict([[90]]))

"""##Visualizing the results in higher resolution"""

X_grid = np.arange(min(X), max(X), 0.1)
X_grid = X_grid.reshape(len(X_grid), 1)
plt.scatter(X, y, color='red')
plt.plot(X_grid, regressor_10.predict(X_grid), color='blue')
plt.plot(X_grid, regressor_50.predict(X_grid), color='black')
plt.plot(X_grid, regressor_100.predict(X_grid), color='green')
plt.title('Restaurant Location Score vs Daily Revenue')
plt.xlabel('Restaurant Location Score')
plt.ylabel('Daily Revenue')
plt.show()

"""###Visualizing the results in higher resolution for model with 10 estimators"""

X_grid = np.arange(min(X), max(X), 0.1)
X_grid = X_grid.reshape(len(X_grid), 1)
plt.scatter(X, y, color='red')
plt.plot(X_grid, regressor_10.predict(X_grid), color='blue')
plt.title('Restaurant Location Score vs Daily Revenue')
plt.xlabel('Restaurant Location Score')
plt.ylabel('Daily Revenue')
plt.show()

"""###Visualizing the results in higher resolution for model with 50 estimators"""

X_grid = np.arange(min(X), max(X), 0.1)
X_grid = X_grid.reshape(len(X_grid), 1)
plt.scatter(X, y, color='red')
plt.plot(X_grid, regressor_50.predict(X_grid), color='blue')
plt.title('Restaurant Location Score vs Daily Revenue')
plt.xlabel('Restaurant Location Score')
plt.ylabel('Daily Revenue')
plt.show()

"""###Visualizing the results in higher resolution for model with 100 estimators"""

X_grid = np.arange(min(X), max(X), 0.1)
X_grid = X_grid.reshape(len(X_grid), 1)
plt.scatter(X, y, color='red')
plt.plot(X_grid, regressor_100.predict(X_grid), color='blue')
plt.title('Restaurant Location Score vs Daily Revenue')
plt.xlabel('Restaurant Location Score')
plt.ylabel('Daily Revenue')
plt.show()

"""##Performance Metrics"""

from sklearn.metrics import r2_score

"""###R<sup>2</sup> scores"""

#Model with 10 estimators
print(r2_score(y, regressor_10.predict(X)))

#Model with 50 estimators
print(r2_score(y, regressor_50.predict(X)))

#Model with 100 estimators
print(r2_score(y, regressor_100.predict(X)))