# -*- coding: utf-8 -*-
"""Exercise 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10TASWFval78z5TcjGMpTX2OXPd1wXfOK

#Exercise 1

Goal: Implement and verify a polynomial regression (degree 4) pipeline on Position_Salaries.csv

##Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""##Importing the dataset"""

dataset = pd.read_csv('Position_Salaries.csv')

dataset.head()

print(dataset)

"""##Creating the matrix of features"""

X = dataset.iloc[:, 1:-1].values

X.shape

print(X)

"""##Creating the dependent variable vector"""

y = dataset.iloc[:, -1].values

y.shape

print(y)

"""##Creating a new matrix of features"""

from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree=4)
X_poly = poly_reg.fit_transform(X)

X_poly.shape

print(X_poly)

"""##Building the model"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

"""##Training the model"""

regressor.fit(X_poly, y)

"""##Visualizing the results"""

plt.scatter(X, y, color='red')
plt.plot(X, regressor.predict(X_poly), color='blue')
plt.title('Position Levels vs Salaries (degree=4)')
plt.xlabel('Position Levels')
plt.ylabel('Salaries')
plt.show()

"""##Making a single prediction"""

pred_6_5 = regressor.predict(poly_reg.transform([[6.5]]))

print(pred_6_5)

"""##Calculating the values of the coefficients

###Calculating b<sub>0</sub> (y-intercept)
"""

print(regressor.intercept_)

"""###Calculating b<sub>i</sub> (slope coefficients)"""

print(regressor.coef_)