# -*- coding: utf-8 -*-
"""Exercise 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GGifLU9CLIQyfZE76fUp1Jl8aFisi12J

#Exercise 1

Goal: Build, train, and verify a simple linear regression model on Salary_Data.csv.

##Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""##Importing the dataset"""

dataset = pd.read_csv('Salary_Data.csv')

print(dataset)

"""##Creating the matrix of features"""

X = dataset.iloc[:, :-1].values

print(X)

"""##Creating the dependent variable vector"""

y = dataset.iloc[:, -1].values

print(y)

"""##Splitting the dataset into training set and test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

print(X_train)

print(X_test)

print(y_train)

print(y_test)

"""##Building the model"""

from sklearn.linear_model import LinearRegression
slr = LinearRegression()

"""##Training the model"""

slr.fit(X_train, y_train)

"""##Predicting the test set results"""

y_pred = slr.predict(X_test)

print(y_pred)

"""##Visualizing the training set results"""

plt.scatter(X_train, y_train, color='red')
plt.plot(X_train, slr.predict(X_train), color='blue')
plt.title('Years of Experience vs Salary (Training Set)')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()

"""##Visualizing the test set results"""

plt.scatter(X_test, y_test, color='red')
plt.plot(X_test, y_pred, color='blue')
plt.title('Years of Experience vs Salary (Test set)')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()

"""##Making a single prediction"""

#Predict the salary of an employee having 12 years of experience
print(slr.predict([[12]]))

"""##Calculating the values of the coefficients

###Calculating b₀ (y-intercept)
"""

print(slr.intercept_)

"""###Calculating b₁ (slope coefficient)"""

print(slr.coef_)