# -*- coding: utf-8 -*-
"""Polynomial Regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rcHRRLwKhsehREAg1RUNEFi5hxUnjtjq

#Polynomial Regression

##Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""##Importing the dataset"""

dataset = pd.read_csv('Position_Salaries.csv')

print(dataset)

"""##Creating the matrix of features"""

X = dataset.iloc[:, 1:-1].values

print(X)

"""##Creating the dependent variable vector"""

y = dataset.iloc[:, -1].values

print(y)

"""##Creating a new matrix of features"""

from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree=4)
X_poly = poly_reg.fit_transform(X)

print(X_poly)

"""##Building the model"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

"""##Training the model"""

regressor.fit(X_poly, y)

"""##Visualizing the results"""

plt.scatter(X, y, color='red')
plt.plot(X, regressor.predict(X_poly), color='blue')
plt.title('Position Levels vs Salary')
plt.xlabel('Position Levels')
plt.ylabel('Salary')
plt.show()

"""##Making a single prediction"""

print(regressor.predict(poly_reg.transform([[6.5]])))