# -*- coding: utf-8 -*-
"""Exercise 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LSiF92YBQMd-YF1sl4TwNhMtkaHI8Vy3

#Exercise: Property Age vs House Value

Goal: Build a decision tree regression model to predict house values based on property age, capturing the non-linear depreciation and appreciation patterns.

##Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""##Importing the dataset"""

dataset = pd.read_csv('property_value_patterns.csv')

print(dataset)

"""##Creating the matrix of features"""

X = dataset.iloc[:, :-1].values

print(X)

"""##Creating the dependent variable vector"""

y = dataset.iloc[:, -1].values

print(y)

"""##Building the model"""

from sklearn.tree import DecisionTreeRegressor

#max_depth = 2
regressor_2 = DecisionTreeRegressor(max_depth=2, random_state=0)

#max_depth = 3
regressor_3 = DecisionTreeRegressor(max_depth=3, random_state=0)

#max_depth = 5
regressor_5 = DecisionTreeRegressor(max_depth=5, random_state=0)

"""##Training the model"""

#max_depth = 2
regressor_2.fit(X, y)

#max_depth = 3
regressor_3.fit(X, y)

#max_depth = 5
regressor_5.fit(X, y)

"""##Making a prediction"""

#Predict value for 7-year-old property
print(regressor_2.predict([[7]]))
#Predict value for 45-year-old property
print(regressor_2.predict([[45]]))

#Predict value for 7-year-old property
print(regressor_3.predict([[7]]))
#Predict value for 45-year-old property
print(regressor_3.predict([[45]]))

#Predict value for 7-year-old property
print(regressor_5.predict([[7]]))
#Predict value for 45-year-old property
print(regressor_5.predict([[45]]))

"""##Visualizing the results in higher resolution"""

X_grid = np.arange(min(X), max(X), 0.1)
X_grid = X_grid.reshape(len(X_grid), 1)
plt.scatter(X, y, color='red')
plt.plot(X_grid, regressor_2.predict(X_grid), color='blue')
plt.plot(X_grid, regressor_3.predict(X_grid), color='black')
plt.plot(X_grid, regressor_5.predict(X_grid), color='green')
plt.title('Property Age vs House Value')
plt.xlabel('Property Age')
plt.ylabel('House value')
plt.show()

X_grid = np.arange(min(X), max(X), 0.1)
X_grid = X_grid.reshape(len(X_grid), 1)
plt.scatter(X, y, color='red')
plt.plot(X_grid, regressor_2.predict(X_grid), color='blue')
plt.title('Property Age vs House Value (max_depth=2)')
plt.xlabel('Property Age')
plt.ylabel('House value')
plt.show()

X_grid = np.arange(min(X), max(X), 0.1)
X_grid = X_grid.reshape(len(X_grid), 1)
plt.scatter(X, y, color='red')
plt.plot(X_grid, regressor_3.predict(X_grid), color='blue')
plt.title('Property Age vs House Value (max_depth=3)')
plt.xlabel('Property Age')
plt.ylabel('House value')
plt.show()

X_grid = np.arange(min(X), max(X), 0.1)
X_grid = X_grid.reshape(len(X_grid), 1)
plt.scatter(X, y, color='red')
plt.plot(X_grid, regressor_5.predict(X_grid), color='blue')
plt.title('Property Age vs House Value (max_depth=5)')
plt.xlabel('Property Age')
plt.ylabel('House value')
plt.show()