# -*- coding: utf-8 -*-
"""Exercise 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FpSp5o65xHTMcX5fZxsyosoNeGekiksT

#Exercise: Engine RPM vs Fuel Efficiency

Goal: Build an SVR model to predict fuel efficiency based on engine RPM, capturing the non-linear relationship where efficiency peaks at optimal RPM ranges.

##Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""##Importing the dataset"""

dataset = pd.read_csv('engine_efficiency_curve.csv')

print(dataset)

"""##Creating the matrix of features"""

X = dataset.iloc[:, :-1].values

print(X)

"""##Creating the dependent variable vector"""

y = dataset.iloc[:, -1].values

print(y)

"""##Transforming the dependent variable vector into a 2D array"""

y = y.reshape(-1, 1)

print(y)

"""##Feature Scaling"""

from sklearn.preprocessing import StandardScaler

"""###Feature scaling on matrix of features"""

sc_X = StandardScaler()
X_scaled = sc_X.fit_transform(X)

print(X_scaled)

"""###Feature scaling on dependent variable vector"""

sc_y = StandardScaler()
y_scaled = sc_y.fit_transform(y)

print(y_scaled)

"""##Building the model

###Building the model using 'linear' kernel
"""

#kernel='linear'
from sklearn.svm import SVR
regressor_linear = SVR(kernel='linear')

"""###Building the model using 'poly' kernel"""

#kernel='poly'
from sklearn.svm import SVR
regressor_poly = SVR(kernel='poly')

"""###Building the model using 'rbf' kernel"""

#kernel='rbf'
from sklearn.svm import SVR
regressor_rbf = SVR(kernel='rbf')

"""###Building the model using 'sigmoid' kernel"""

#kernel='sigmoid'
from sklearn.svm import SVR
regressor_sigmoid = SVR(kernel='sigmoid')

"""##Training the model

###Training the model using 'linear' kernel
"""

regressor_linear.fit(X_scaled, y_scaled)

"""###Training the model using 'poly' kernel"""

regressor_poly.fit(X_scaled, y_scaled)

"""###Training the model using 'rbf' kernel"""

regressor_rbf.fit(X_scaled, y_scaled)

"""###Training the model using 'sigmoid' kernel"""

regressor_sigmoid.fit(X_scaled, y_scaled)

"""##Making predictions

###Making predictions using 'linear' kernel SVR model
"""

#Predict fuel efficiency at 2800 RPM
print(sc_y.inverse_transform(regressor_linear.predict(sc_X.transform([[2800]])).reshape(-1, 1)))
#Predict fuel efficiency at 4800 RPM
print(sc_y.inverse_transform(regressor_linear.predict(sc_X.transform([[4800]])).reshape(-1, 1)))

"""###Making predictions using 'poly' kernel SVR model"""

#Predict fuel efficiency at 2800 RPM
print(sc_y.inverse_transform(regressor_poly.predict(sc_X.transform([[2800]])).reshape(-1, 1)))
#Predict fuel efficiency at 4800 RPM
print(sc_y.inverse_transform(regressor_poly.predict(sc_X.transform([[4800]])).reshape(-1, 1)))

"""###Making predictions using 'rbf' kernel SVR model"""

#Predict fuel efficiency at 2800 RPM
print(sc_y.inverse_transform(regressor_rbf.predict(sc_X.transform([[2800]])).reshape(-1, 1)))
#Predict fuel efficiency at 4800 RPM
print(sc_y.inverse_transform(regressor_rbf.predict(sc_X.transform([[4800]])).reshape(-1, 1)))

"""###Making predictions using 'sigmoid' kernel SVR model"""

#Predict fuel efficiency at 2800 RPM
print(sc_y.inverse_transform(regressor_sigmoid.predict(sc_X.transform([[2800]])).reshape(-1, 1)))
#Predict fuel efficiency at 4800 RPM
print(sc_y.inverse_transform(regressor_sigmoid.predict(sc_X.transform([[4800]])).reshape(-1, 1)))

"""##Visualizing the results"""

plt.scatter(X, y, color='red')
plt.plot(X, sc_y.inverse_transform(regressor_linear.predict(X_scaled).reshape(-1, 1)), color='blue')
plt.plot(X, sc_y.inverse_transform(regressor_poly.predict(X_scaled).reshape(-1, 1)), color='yellow')
plt.plot(X, sc_y.inverse_transform(regressor_rbf.predict(X_scaled).reshape(-1, 1)), color='black')
plt.plot(X, sc_y.inverse_transform(regressor_sigmoid.predict(X_scaled).reshape(-1, 1)), color='green')
plt.title('Engine RPM vs Fuel Efficiency')
plt.xlabel('Engine RPM')
plt.ylabel('Fuel Efficiency')
plt.show()

"""###Visualizing the results using 'linear' kernel SVR model"""

plt.scatter(X, y, color='red')
plt.plot(X, sc_y.inverse_transform(regressor_linear.predict(X_scaled).reshape(-1, 1)), color='blue')
plt.title('Engine RPM vs Fuel Efficiency (Kernel=linear)')
plt.xlabel('Engine RPM')
plt.ylabel('Fuel Efficiency')
plt.show()

"""###Visualizing the results using 'poly' kernel SVR model"""

plt.scatter(X, y, color='red')
plt.plot(X, sc_y.inverse_transform(regressor_poly.predict(X_scaled).reshape(-1, 1)), color='blue')
plt.title('Engine RPM vs Fuel Efficiency (Kernel=poly)')
plt.xlabel('Engine RPM')
plt.ylabel('Fuel Efficiency')
plt.show()

"""###Visualizing the results using 'rbf' kernel SVR model"""

plt.scatter(X, y, color='red')
plt.plot(X, sc_y.inverse_transform(regressor_rbf.predict(X_scaled).reshape(-1, 1)), color='blue')
plt.title('Engine RPM vs Fuel Efficiency (Kernel=rbf)')
plt.xlabel('Engine RPM')
plt.ylabel('Fuel Efficiency')
plt.show()

"""###Visualizing the results using 'sigmoid' kernel SVR model"""

plt.scatter(X, y, color='red')
plt.plot(X, sc_y.inverse_transform(regressor_sigmoid.predict(X_scaled).reshape(-1, 1)), color='blue')
plt.title('Engine RPM vs Fuel Efficiency (Kernel=sigmoid)')
plt.xlabel('Engine RPM')
plt.ylabel('Fuel Efficiency')
plt.show()